### ISSUE TITLE
Pas vraiment une issue...

### ISSUE THREAD

**Issue by Lafrite** [dane-lyon/clients-linux-scribe#1]
Bonjour,

Je suis référent TICE dans un collège de Mayotte où nous utilisons vos scripts. Et ils marchent plutôt bien. Merci pour votre travail.

J'ai quand même un peu modifié vos scipts. J'espère que ça ne vous dérange pas si je vous fait quelques _pull resquests_ .

Merci encore pour votre travail
B.Bertrand

**Comment by dane-lyon** [comment]
Vous pouvez faire toutes les modifs qui vous intéresses en forkant notre projet mais nous n'intégrerons pas vos changements dans nos scripts de notre coté car ils ne font pas consensus.

cordialement;
