### ISSUE TITLE
mint 18 cinnamon 32bits

### ISSUE THREAD

**Issue by deck0** [dane-lyon/clients-linux-scribe#13]
Bonjour, 
Je viens de tester le script pour intégrer un mint 18 sur un scribe 2.5.2. Le script semble bien se dérouler (du moins, pas d'erreur retournée) mais après le redémarrage, j'ai toujours l'utilisateur local de proposé. Si je fais F1 pour changer d'utilisateur et que j'indique un compte présent sur le serveur, j'ai un échec de connexion.
En regardant le script j'ai vu que
`apt-get install -y ldap-auth-client libpam-mount cifs-utils nscd numlockx unattended-upgrades`
semble passer à la trappe et que les fichiers de configurations ne sont pas renseignés comme demandé par le script.
J'ai testé depuis 2 installations propres de mint, c'est la même chose.
Auriez-vous une piste?
Merci

**Comment by CollegeRenan** [comment]
Bonsoir,

j'utilise le script sur une vingtaine de machines sous Mint 17.3 ou 18.1 
avec un scribe 2.6.32-73 sous Eole et je n'ai pas rencontré ce type de 
problème.

En revanche, j'ai eu des soucis à cause de la fenêtre de connexion 
(défilement de tous les utilisateurs pour trouver le bon qui bloquait 
tout). La solution a été de sélectionner la fenêtre Elegant en décochant 
se souvenir du dernier utilisateur logué.

Voilà, si ces informations peuvent être utiles.

Cordialement

*David Benveniste
Principal

Collège E. Renan
rue de la Corderie
**22220 **Minihy-Tréguier
tel 02 96 92 31 89*

**Comment by simbd** [comment]
Le script d'intégration a déjà été testé avec Mint 18 et il fonctionne correctement. D'ailleurs il n'y a même pas besoin de modifier le thème de la fenêtre car le script le fait a votre place en modifiant le fichier de configuration de MDM.

Par contre la nouvelle version de Mint (la 18.2) n'a pas encore été testé sachant qu'ils ont fait un changement sur cette version : ils n'utilisent plus MDM mais LightDM.

"CollegeRenan" j'ai vu que tu as forké une vieille version du script, attention il ne faut pas utiliser cette version, elle a été modifié depuis, il faut utiliser la version de notre dépôt qui est maj de temps en temps (et qui n'a pas le problème que tu décris mais qui était présent sur l'ancienne version dans ton dépôt).

**Comment by simbd** [comment]
18.2 validé a l'instant

**Comment by deck0** [comment]
Merci pour les retours. Je viens de tester avec la 18.1, j'ai le même pb... Je reteste demain sans passer le script de post installation...

**Comment by simbd** [comment]
J'ai fais une correction hier car il y avait une balise "fi" qui a été supprimé par erreur, il faudrait retester en téléchargeant bien la dernière version du Script (1.0.11)

**Comment by deck0** [comment]
Ça fonctionne! Merci beaucoup pour la correction, j'avais beau parcourir le code je ne voyais pas d'où venait le pb.
