### ISSUE TITLE
Fixer volume casque et micro

### ISSUE THREAD

**Issue by ghost** [dane-lyon/clients-linux-scribe#15]
Bonjour (une deuxième fois)...
Nos petits collégiens utilisent audacity pour s’enregistrer en langues vivantes.
Lorsqu’ils ouvrent une session, je souhaiterai que le niveau du casque soit fixé à 100%, et, après avoir trouvé le bon niveau, je souhaiterai que celui du micro le soit également.
Cela permettrait aux profs de langues de ne pas s’arracher les cheveux en passant derrière les élèves pour trouver pourquoi « ça marche pas !!! ».

D’ailleurs, il n’y a pas forcément un lien entre le contrôle des niveaux sous audacity et Linux mint (obligation d’aller dans les paramètres du son pour augmenter le niveau du micro)

Merci pour votre excellent travail qui permet de faire revivre notre vieille salle informatique 

Jonathan

**Comment by simbd** [comment]
Le réglage du niveau sonore du micro se fait dans les paramètres de son, normalement ça sera sauvegardé pour le compte sur le poste.

**Comment by simbd** [comment]
faire demande sur le forum francophone d'Ubuntu si besoin.

**Comment by oliviercalpetard** [comment]
suite à la mise à jours de esubunutu, une nouvelle fonctionnalité a été ajoutée, on peut y executer un script shell perso à l'ouverture de session avec les droits utilisateur.
par exemple pour le son
pactl set-sink-mute @DEFAULT_SINK@ 0
pactl set-sink-volume @DEFAULT_SINK@ +80%
